/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcReqUserLoginWithCaptchaField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcReqUserLoginWithCaptchaField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcReqUserLoginWithCaptchaField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcReqUserLoginWithCaptchaField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_TradingDay_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_UserID_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_Password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_Password_get(swigCPtr, this);
  }

  public void setUserProductInfo(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_UserProductInfo_set(swigCPtr, this, value);
  }

  public String getUserProductInfo() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_UserProductInfo_get(swigCPtr, this);
  }

  public void setInterfaceProductInfo(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_InterfaceProductInfo_set(swigCPtr, this, value);
  }

  public String getInterfaceProductInfo() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_InterfaceProductInfo_get(swigCPtr, this);
  }

  public void setProtocolInfo(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_ProtocolInfo_set(swigCPtr, this, value);
  }

  public String getProtocolInfo() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_ProtocolInfo_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_MacAddress_get(swigCPtr, this);
  }

  public void setClientIPAddress(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_ClientIPAddress_set(swigCPtr, this, value);
  }

  public String getClientIPAddress() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_ClientIPAddress_get(swigCPtr, this);
  }

  public void setLoginRemark(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_LoginRemark_set(swigCPtr, this, value);
  }

  public String getLoginRemark() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_LoginRemark_get(swigCPtr, this);
  }

  public void setCaptcha(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_Captcha_set(swigCPtr, this, value);
  }

  public String getCaptcha() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_Captcha_get(swigCPtr, this);
  }

  public void setClientIPPort(int value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_ClientIPPort_set(swigCPtr, this, value);
  }

  public int getClientIPPort() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginWithCaptchaField_ClientIPPort_get(swigCPtr, this);
  }

  public CThostFtdcReqUserLoginWithCaptchaField() {
    this(ThostTradeApiJNI.new_CThostFtdcReqUserLoginWithCaptchaField(), true);
  }

}
