/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcExchangeRateField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcExchangeRateField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcExchangeRateField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcExchangeRateField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcExchangeRateField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcExchangeRateField_BrokerID_get(swigCPtr, this);
  }

  public void setFromCurrencyID(String value) {
    ThostTradeApiJNI.CThostFtdcExchangeRateField_FromCurrencyID_set(swigCPtr, this, value);
  }

  public String getFromCurrencyID() {
    return ThostTradeApiJNI.CThostFtdcExchangeRateField_FromCurrencyID_get(swigCPtr, this);
  }

  public void setFromCurrencyUnit(double value) {
    ThostTradeApiJNI.CThostFtdcExchangeRateField_FromCurrencyUnit_set(swigCPtr, this, value);
  }

  public double getFromCurrencyUnit() {
    return ThostTradeApiJNI.CThostFtdcExchangeRateField_FromCurrencyUnit_get(swigCPtr, this);
  }

  public void setToCurrencyID(String value) {
    ThostTradeApiJNI.CThostFtdcExchangeRateField_ToCurrencyID_set(swigCPtr, this, value);
  }

  public String getToCurrencyID() {
    return ThostTradeApiJNI.CThostFtdcExchangeRateField_ToCurrencyID_get(swigCPtr, this);
  }

  public void setExchangeRate(double value) {
    ThostTradeApiJNI.CThostFtdcExchangeRateField_ExchangeRate_set(swigCPtr, this, value);
  }

  public double getExchangeRate() {
    return ThostTradeApiJNI.CThostFtdcExchangeRateField_ExchangeRate_get(swigCPtr, this);
  }

  public CThostFtdcExchangeRateField() {
    this(ThostTradeApiJNI.new_CThostFtdcExchangeRateField(), true);
  }

}
