/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcSyncFundMortgageField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncFundMortgageField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncFundMortgageField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcSyncFundMortgageField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMortgageSeqNo(String value) {
    ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_MortgageSeqNo_set(swigCPtr, this, value);
  }

  public String getMortgageSeqNo() {
    return ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_MortgageSeqNo_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_InvestorID_get(swigCPtr, this);
  }

  public void setFromCurrencyID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_FromCurrencyID_set(swigCPtr, this, value);
  }

  public String getFromCurrencyID() {
    return ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_FromCurrencyID_get(swigCPtr, this);
  }

  public void setMortgageAmount(double value) {
    ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_MortgageAmount_set(swigCPtr, this, value);
  }

  public double getMortgageAmount() {
    return ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_MortgageAmount_get(swigCPtr, this);
  }

  public void setToCurrencyID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_ToCurrencyID_set(swigCPtr, this, value);
  }

  public String getToCurrencyID() {
    return ThostTradeApiJNI.CThostFtdcSyncFundMortgageField_ToCurrencyID_get(swigCPtr, this);
  }

  public CThostFtdcSyncFundMortgageField() {
    this(ThostTradeApiJNI.new_CThostFtdcSyncFundMortgageField(), true);
  }

}
