/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcRspGenUserTextField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcRspGenUserTextField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcRspGenUserTextField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcRspGenUserTextField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUserTextSeq(int value) {
    ThostTradeApiJNI.CThostFtdcRspGenUserTextField_UserTextSeq_set(swigCPtr, this, value);
  }

  public int getUserTextSeq() {
    return ThostTradeApiJNI.CThostFtdcRspGenUserTextField_UserTextSeq_get(swigCPtr, this);
  }

  public CThostFtdcRspGenUserTextField() {
    this(ThostTradeApiJNI.new_CThostFtdcRspGenUserTextField(), true);
  }

}
