/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcSyncDeltaDceCombInstrumentField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncDeltaDceCombInstrumentField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncDeltaDceCombInstrumentField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcSyncDeltaDceCombInstrumentField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCombInstrumentID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_CombInstrumentID_set(swigCPtr, this, value);
  }

  public String getCombInstrumentID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_CombInstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_ExchangeID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setTradeGroupID(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_TradeGroupID_set(swigCPtr, this, value);
  }

  public int getTradeGroupID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_TradeGroupID_get(swigCPtr, this);
  }

  public void setCombHedgeFlag(char value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_CombHedgeFlag_set(swigCPtr, this, value);
  }

  public char getCombHedgeFlag() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_CombHedgeFlag_get(swigCPtr, this);
  }

  public void setCombinationType(char value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_CombinationType_set(swigCPtr, this, value);
  }

  public char getCombinationType() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_CombinationType_get(swigCPtr, this);
  }

  public void setDirection(char value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_Direction_set(swigCPtr, this, value);
  }

  public char getDirection() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_Direction_get(swigCPtr, this);
  }

  public void setProductID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_ProductID_get(swigCPtr, this);
  }

  public void setXparameter(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_Xparameter_set(swigCPtr, this, value);
  }

  public double getXparameter() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_Xparameter_get(swigCPtr, this);
  }

  public void setActionDirection(char value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_ActionDirection_set(swigCPtr, this, value);
  }

  public char getActionDirection() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_ActionDirection_get(swigCPtr, this);
  }

  public void setSyncDeltaSequenceNo(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_SyncDeltaSequenceNo_set(swigCPtr, this, value);
  }

  public int getSyncDeltaSequenceNo() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDceCombInstrumentField_SyncDeltaSequenceNo_get(swigCPtr, this);
  }

  public CThostFtdcSyncDeltaDceCombInstrumentField() {
    this(ThostTradeApiJNI.new_CThostFtdcSyncDeltaDceCombInstrumentField(), true);
  }

}
