/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcSyncDeltaProductExchRateField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncDeltaProductExchRateField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncDeltaProductExchRateField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcSyncDeltaProductExchRateField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProductID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_ProductID_get(swigCPtr, this);
  }

  public void setQuoteCurrencyID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_QuoteCurrencyID_set(swigCPtr, this, value);
  }

  public String getQuoteCurrencyID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_QuoteCurrencyID_get(swigCPtr, this);
  }

  public void setExchangeRate(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_ExchangeRate_set(swigCPtr, this, value);
  }

  public double getExchangeRate() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_ExchangeRate_get(swigCPtr, this);
  }

  public void setActionDirection(char value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_ActionDirection_set(swigCPtr, this, value);
  }

  public char getActionDirection() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_ActionDirection_get(swigCPtr, this);
  }

  public void setSyncDeltaSequenceNo(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_SyncDeltaSequenceNo_set(swigCPtr, this, value);
  }

  public int getSyncDeltaSequenceNo() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaProductExchRateField_SyncDeltaSequenceNo_get(swigCPtr, this);
  }

  public CThostFtdcSyncDeltaProductExchRateField() {
    this(ThostTradeApiJNI.new_CThostFtdcSyncDeltaProductExchRateField(), true);
  }

}
