/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcRspGenUserCaptchaField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcRspGenUserCaptchaField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcRspGenUserCaptchaField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcRspGenUserCaptchaField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcRspGenUserCaptchaField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcRspGenUserCaptchaField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ThostTradeApiJNI.CThostFtdcRspGenUserCaptchaField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ThostTradeApiJNI.CThostFtdcRspGenUserCaptchaField_UserID_get(swigCPtr, this);
  }

  public void setCaptchaInfoLen(int value) {
    ThostTradeApiJNI.CThostFtdcRspGenUserCaptchaField_CaptchaInfoLen_set(swigCPtr, this, value);
  }

  public int getCaptchaInfoLen() {
    return ThostTradeApiJNI.CThostFtdcRspGenUserCaptchaField_CaptchaInfoLen_get(swigCPtr, this);
  }

  public void setCaptchaInfo(String value) {
    ThostTradeApiJNI.CThostFtdcRspGenUserCaptchaField_CaptchaInfo_set(swigCPtr, this, value);
  }

  public String getCaptchaInfo() {
    return ThostTradeApiJNI.CThostFtdcRspGenUserCaptchaField_CaptchaInfo_get(swigCPtr, this);
  }

  public CThostFtdcRspGenUserCaptchaField() {
    this(ThostTradeApiJNI.new_CThostFtdcRspGenUserCaptchaField(), true);
  }

}
