/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcRiskSettleInvstPositionField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcRiskSettleInvstPositionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcRiskSettleInvstPositionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcRiskSettleInvstPositionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_InstrumentID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_InvestorID_get(swigCPtr, this);
  }

  public void setPosiDirection(char value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PosiDirection_set(swigCPtr, this, value);
  }

  public char getPosiDirection() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PosiDirection_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_HedgeFlag_get(swigCPtr, this);
  }

  public void setPositionDate(char value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PositionDate_set(swigCPtr, this, value);
  }

  public char getPositionDate() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PositionDate_get(swigCPtr, this);
  }

  public void setYdPosition(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_YdPosition_set(swigCPtr, this, value);
  }

  public int getYdPosition() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_YdPosition_get(swigCPtr, this);
  }

  public void setPosition(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_Position_set(swigCPtr, this, value);
  }

  public int getPosition() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_Position_get(swigCPtr, this);
  }

  public void setLongFrozen(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_LongFrozen_set(swigCPtr, this, value);
  }

  public int getLongFrozen() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_LongFrozen_get(swigCPtr, this);
  }

  public void setShortFrozen(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_ShortFrozen_set(swigCPtr, this, value);
  }

  public int getShortFrozen() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_ShortFrozen_get(swigCPtr, this);
  }

  public void setLongFrozenAmount(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_LongFrozenAmount_set(swigCPtr, this, value);
  }

  public double getLongFrozenAmount() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_LongFrozenAmount_get(swigCPtr, this);
  }

  public void setShortFrozenAmount(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_ShortFrozenAmount_set(swigCPtr, this, value);
  }

  public double getShortFrozenAmount() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_ShortFrozenAmount_get(swigCPtr, this);
  }

  public void setOpenVolume(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_OpenVolume_set(swigCPtr, this, value);
  }

  public int getOpenVolume() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_OpenVolume_get(swigCPtr, this);
  }

  public void setCloseVolume(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseVolume_set(swigCPtr, this, value);
  }

  public int getCloseVolume() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseVolume_get(swigCPtr, this);
  }

  public void setOpenAmount(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_OpenAmount_set(swigCPtr, this, value);
  }

  public double getOpenAmount() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_OpenAmount_get(swigCPtr, this);
  }

  public void setCloseAmount(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseAmount_set(swigCPtr, this, value);
  }

  public double getCloseAmount() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseAmount_get(swigCPtr, this);
  }

  public void setPositionCost(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PositionCost_set(swigCPtr, this, value);
  }

  public double getPositionCost() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PositionCost_get(swigCPtr, this);
  }

  public void setPreMargin(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PreMargin_set(swigCPtr, this, value);
  }

  public double getPreMargin() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PreMargin_get(swigCPtr, this);
  }

  public void setUseMargin(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_UseMargin_set(swigCPtr, this, value);
  }

  public double getUseMargin() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_UseMargin_get(swigCPtr, this);
  }

  public void setFrozenMargin(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_FrozenMargin_set(swigCPtr, this, value);
  }

  public double getFrozenMargin() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_FrozenMargin_get(swigCPtr, this);
  }

  public void setFrozenCash(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_FrozenCash_set(swigCPtr, this, value);
  }

  public double getFrozenCash() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_FrozenCash_get(swigCPtr, this);
  }

  public void setFrozenCommission(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_FrozenCommission_set(swigCPtr, this, value);
  }

  public double getFrozenCommission() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_FrozenCommission_get(swigCPtr, this);
  }

  public void setCashIn(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CashIn_set(swigCPtr, this, value);
  }

  public double getCashIn() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CashIn_get(swigCPtr, this);
  }

  public void setCommission(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_Commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_Commission_get(swigCPtr, this);
  }

  public void setCloseProfit(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseProfit_set(swigCPtr, this, value);
  }

  public double getCloseProfit() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseProfit_get(swigCPtr, this);
  }

  public void setPositionProfit(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PositionProfit_set(swigCPtr, this, value);
  }

  public double getPositionProfit() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PositionProfit_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_SettlementPrice_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_SettlementID_get(swigCPtr, this);
  }

  public void setOpenCost(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_OpenCost_set(swigCPtr, this, value);
  }

  public double getOpenCost() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_OpenCost_get(swigCPtr, this);
  }

  public void setExchangeMargin(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_ExchangeMargin_set(swigCPtr, this, value);
  }

  public double getExchangeMargin() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_ExchangeMargin_get(swigCPtr, this);
  }

  public void setCombPosition(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CombPosition_set(swigCPtr, this, value);
  }

  public int getCombPosition() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CombPosition_get(swigCPtr, this);
  }

  public void setCombLongFrozen(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CombLongFrozen_set(swigCPtr, this, value);
  }

  public int getCombLongFrozen() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CombLongFrozen_get(swigCPtr, this);
  }

  public void setCombShortFrozen(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CombShortFrozen_set(swigCPtr, this, value);
  }

  public int getCombShortFrozen() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CombShortFrozen_get(swigCPtr, this);
  }

  public void setCloseProfitByDate(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseProfitByDate_set(swigCPtr, this, value);
  }

  public double getCloseProfitByDate() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseProfitByDate_get(swigCPtr, this);
  }

  public void setCloseProfitByTrade(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseProfitByTrade_set(swigCPtr, this, value);
  }

  public double getCloseProfitByTrade() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_CloseProfitByTrade_get(swigCPtr, this);
  }

  public void setTodayPosition(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_TodayPosition_set(swigCPtr, this, value);
  }

  public int getTodayPosition() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_TodayPosition_get(swigCPtr, this);
  }

  public void setMarginRateByMoney(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_MarginRateByMoney_set(swigCPtr, this, value);
  }

  public double getMarginRateByMoney() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_MarginRateByMoney_get(swigCPtr, this);
  }

  public void setMarginRateByVolume(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_MarginRateByVolume_set(swigCPtr, this, value);
  }

  public double getMarginRateByVolume() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_MarginRateByVolume_get(swigCPtr, this);
  }

  public void setStrikeFrozen(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_StrikeFrozen_set(swigCPtr, this, value);
  }

  public int getStrikeFrozen() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_StrikeFrozen_get(swigCPtr, this);
  }

  public void setStrikeFrozenAmount(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_StrikeFrozenAmount_set(swigCPtr, this, value);
  }

  public double getStrikeFrozenAmount() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_StrikeFrozenAmount_get(swigCPtr, this);
  }

  public void setAbandonFrozen(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_AbandonFrozen_set(swigCPtr, this, value);
  }

  public int getAbandonFrozen() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_AbandonFrozen_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_ExchangeID_get(swigCPtr, this);
  }

  public void setYdStrikeFrozen(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_YdStrikeFrozen_set(swigCPtr, this, value);
  }

  public int getYdStrikeFrozen() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_YdStrikeFrozen_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_InvestUnitID_get(swigCPtr, this);
  }

  public void setPositionCostOffset(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PositionCostOffset_set(swigCPtr, this, value);
  }

  public double getPositionCostOffset() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_PositionCostOffset_get(swigCPtr, this);
  }

  public void setTasPosition(int value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_TasPosition_set(swigCPtr, this, value);
  }

  public int getTasPosition() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_TasPosition_get(swigCPtr, this);
  }

  public void setTasPositionCost(double value) {
    ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_TasPositionCost_set(swigCPtr, this, value);
  }

  public double getTasPositionCost() {
    return ThostTradeApiJNI.CThostFtdcRiskSettleInvstPositionField_TasPositionCost_get(swigCPtr, this);
  }

  public CThostFtdcRiskSettleInvstPositionField() {
    this(ThostTradeApiJNI.new_CThostFtdcRiskSettleInvstPositionField(), true);
  }

}
