/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcTradingCodeField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcTradingCodeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcTradingCodeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcTradingCodeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInvestorID(String value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_InvestorID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_BrokerID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_ExchangeID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_ClientID_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_IsActive_get(swigCPtr, this);
  }

  public void setClientIDType(char value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_ClientIDType_set(swigCPtr, this, value);
  }

  public char getClientIDType() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_ClientIDType_get(swigCPtr, this);
  }

  public void setBranchID(String value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_BranchID_set(swigCPtr, this, value);
  }

  public String getBranchID() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_BranchID_get(swigCPtr, this);
  }

  public void setBizType(char value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_BizType_set(swigCPtr, this, value);
  }

  public char getBizType() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_BizType_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    ThostTradeApiJNI.CThostFtdcTradingCodeField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return ThostTradeApiJNI.CThostFtdcTradingCodeField_InvestUnitID_get(swigCPtr, this);
  }

  public CThostFtdcTradingCodeField() {
    this(ThostTradeApiJNI.new_CThostFtdcTradingCodeField(), true);
  }

}
