/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcReqUserLoginField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcReqUserLoginField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcReqUserLoginField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcReqUserLoginField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_TradingDay_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_UserID_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_Password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_Password_get(swigCPtr, this);
  }

  public void setUserProductInfo(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_UserProductInfo_set(swigCPtr, this, value);
  }

  public String getUserProductInfo() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_UserProductInfo_get(swigCPtr, this);
  }

  public void setInterfaceProductInfo(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_InterfaceProductInfo_set(swigCPtr, this, value);
  }

  public String getInterfaceProductInfo() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_InterfaceProductInfo_get(swigCPtr, this);
  }

  public void setProtocolInfo(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_ProtocolInfo_set(swigCPtr, this, value);
  }

  public String getProtocolInfo() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_ProtocolInfo_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_MacAddress_get(swigCPtr, this);
  }

  public void setOneTimePassword(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_OneTimePassword_set(swigCPtr, this, value);
  }

  public String getOneTimePassword() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_OneTimePassword_get(swigCPtr, this);
  }

  public void setClientIPAddress(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_ClientIPAddress_set(swigCPtr, this, value);
  }

  public String getClientIPAddress() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_ClientIPAddress_get(swigCPtr, this);
  }

  public void setLoginRemark(String value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_LoginRemark_set(swigCPtr, this, value);
  }

  public String getLoginRemark() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_LoginRemark_get(swigCPtr, this);
  }

  public void setClientIPPort(int value) {
    ThostTradeApiJNI.CThostFtdcReqUserLoginField_ClientIPPort_set(swigCPtr, this, value);
  }

  public int getClientIPPort() {
    return ThostTradeApiJNI.CThostFtdcReqUserLoginField_ClientIPPort_get(swigCPtr, this);
  }

  public CThostFtdcReqUserLoginField() {
    this(ThostTradeApiJNI.new_CThostFtdcReqUserLoginField(), true);
  }

}
