/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcTransferBankField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcTransferBankField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcTransferBankField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcTransferBankField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBankID(String value) {
    ThostTradeApiJNI.CThostFtdcTransferBankField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return ThostTradeApiJNI.CThostFtdcTransferBankField_BankID_get(swigCPtr, this);
  }

  public void setBankBrchID(String value) {
    ThostTradeApiJNI.CThostFtdcTransferBankField_BankBrchID_set(swigCPtr, this, value);
  }

  public String getBankBrchID() {
    return ThostTradeApiJNI.CThostFtdcTransferBankField_BankBrchID_get(swigCPtr, this);
  }

  public void setBankName(String value) {
    ThostTradeApiJNI.CThostFtdcTransferBankField_BankName_set(swigCPtr, this, value);
  }

  public String getBankName() {
    return ThostTradeApiJNI.CThostFtdcTransferBankField_BankName_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    ThostTradeApiJNI.CThostFtdcTransferBankField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return ThostTradeApiJNI.CThostFtdcTransferBankField_IsActive_get(swigCPtr, this);
  }

  public CThostFtdcTransferBankField() {
    this(ThostTradeApiJNI.new_CThostFtdcTransferBankField(), true);
  }

}
