/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcSyncDeltaDepthMarketDataField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcSyncDeltaDepthMarketDataField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcSyncDeltaDepthMarketDataField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcSyncDeltaDepthMarketDataField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_TradingDay_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ExchangeID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setLastPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_LastPrice_set(swigCPtr, this, value);
  }

  public double getLastPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_LastPrice_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setPreClosePrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_PreClosePrice_set(swigCPtr, this, value);
  }

  public double getPreClosePrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_PreClosePrice_get(swigCPtr, this);
  }

  public void setPreOpenInterest(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_PreOpenInterest_set(swigCPtr, this, value);
  }

  public double getPreOpenInterest() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_PreOpenInterest_get(swigCPtr, this);
  }

  public void setOpenPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_OpenPrice_set(swigCPtr, this, value);
  }

  public double getOpenPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_OpenPrice_get(swigCPtr, this);
  }

  public void setHighestPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_HighestPrice_set(swigCPtr, this, value);
  }

  public double getHighestPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_HighestPrice_get(swigCPtr, this);
  }

  public void setLowestPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_LowestPrice_set(swigCPtr, this, value);
  }

  public double getLowestPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_LowestPrice_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_Volume_get(swigCPtr, this);
  }

  public void setTurnover(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_Turnover_set(swigCPtr, this, value);
  }

  public double getTurnover() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_Turnover_get(swigCPtr, this);
  }

  public void setOpenInterest(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_OpenInterest_set(swigCPtr, this, value);
  }

  public double getOpenInterest() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_OpenInterest_get(swigCPtr, this);
  }

  public void setClosePrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ClosePrice_set(swigCPtr, this, value);
  }

  public double getClosePrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ClosePrice_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_SettlementPrice_get(swigCPtr, this);
  }

  public void setUpperLimitPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_UpperLimitPrice_set(swigCPtr, this, value);
  }

  public double getUpperLimitPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_UpperLimitPrice_get(swigCPtr, this);
  }

  public void setLowerLimitPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_LowerLimitPrice_set(swigCPtr, this, value);
  }

  public double getLowerLimitPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_LowerLimitPrice_get(swigCPtr, this);
  }

  public void setPreDelta(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_PreDelta_set(swigCPtr, this, value);
  }

  public double getPreDelta() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_PreDelta_get(swigCPtr, this);
  }

  public void setCurrDelta(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_CurrDelta_set(swigCPtr, this, value);
  }

  public double getCurrDelta() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_CurrDelta_get(swigCPtr, this);
  }

  public void setUpdateTime(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_UpdateTime_set(swigCPtr, this, value);
  }

  public String getUpdateTime() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_UpdateTime_get(swigCPtr, this);
  }

  public void setUpdateMillisec(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_UpdateMillisec_set(swigCPtr, this, value);
  }

  public int getUpdateMillisec() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_UpdateMillisec_get(swigCPtr, this);
  }

  public void setBidPrice1(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice1_set(swigCPtr, this, value);
  }

  public double getBidPrice1() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice1_get(swigCPtr, this);
  }

  public void setBidVolume1(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume1_set(swigCPtr, this, value);
  }

  public int getBidVolume1() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume1_get(swigCPtr, this);
  }

  public void setAskPrice1(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice1_set(swigCPtr, this, value);
  }

  public double getAskPrice1() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice1_get(swigCPtr, this);
  }

  public void setAskVolume1(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume1_set(swigCPtr, this, value);
  }

  public int getAskVolume1() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume1_get(swigCPtr, this);
  }

  public void setBidPrice2(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice2_set(swigCPtr, this, value);
  }

  public double getBidPrice2() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice2_get(swigCPtr, this);
  }

  public void setBidVolume2(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume2_set(swigCPtr, this, value);
  }

  public int getBidVolume2() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume2_get(swigCPtr, this);
  }

  public void setAskPrice2(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice2_set(swigCPtr, this, value);
  }

  public double getAskPrice2() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice2_get(swigCPtr, this);
  }

  public void setAskVolume2(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume2_set(swigCPtr, this, value);
  }

  public int getAskVolume2() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume2_get(swigCPtr, this);
  }

  public void setBidPrice3(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice3_set(swigCPtr, this, value);
  }

  public double getBidPrice3() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice3_get(swigCPtr, this);
  }

  public void setBidVolume3(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume3_set(swigCPtr, this, value);
  }

  public int getBidVolume3() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume3_get(swigCPtr, this);
  }

  public void setAskPrice3(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice3_set(swigCPtr, this, value);
  }

  public double getAskPrice3() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice3_get(swigCPtr, this);
  }

  public void setAskVolume3(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume3_set(swigCPtr, this, value);
  }

  public int getAskVolume3() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume3_get(swigCPtr, this);
  }

  public void setBidPrice4(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice4_set(swigCPtr, this, value);
  }

  public double getBidPrice4() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice4_get(swigCPtr, this);
  }

  public void setBidVolume4(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume4_set(swigCPtr, this, value);
  }

  public int getBidVolume4() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume4_get(swigCPtr, this);
  }

  public void setAskPrice4(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice4_set(swigCPtr, this, value);
  }

  public double getAskPrice4() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice4_get(swigCPtr, this);
  }

  public void setAskVolume4(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume4_set(swigCPtr, this, value);
  }

  public int getAskVolume4() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume4_get(swigCPtr, this);
  }

  public void setBidPrice5(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice5_set(swigCPtr, this, value);
  }

  public double getBidPrice5() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidPrice5_get(swigCPtr, this);
  }

  public void setBidVolume5(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume5_set(swigCPtr, this, value);
  }

  public int getBidVolume5() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BidVolume5_get(swigCPtr, this);
  }

  public void setAskPrice5(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice5_set(swigCPtr, this, value);
  }

  public double getAskPrice5() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskPrice5_get(swigCPtr, this);
  }

  public void setAskVolume5(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume5_set(swigCPtr, this, value);
  }

  public int getAskVolume5() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AskVolume5_get(swigCPtr, this);
  }

  public void setAveragePrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AveragePrice_set(swigCPtr, this, value);
  }

  public double getAveragePrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_AveragePrice_get(swigCPtr, this);
  }

  public void setActionDay(String value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ActionDay_set(swigCPtr, this, value);
  }

  public String getActionDay() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ActionDay_get(swigCPtr, this);
  }

  public void setBandingUpperPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BandingUpperPrice_set(swigCPtr, this, value);
  }

  public double getBandingUpperPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BandingUpperPrice_get(swigCPtr, this);
  }

  public void setBandingLowerPrice(double value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BandingLowerPrice_set(swigCPtr, this, value);
  }

  public double getBandingLowerPrice() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_BandingLowerPrice_get(swigCPtr, this);
  }

  public void setActionDirection(char value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ActionDirection_set(swigCPtr, this, value);
  }

  public char getActionDirection() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_ActionDirection_get(swigCPtr, this);
  }

  public void setSyncDeltaSequenceNo(int value) {
    ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_SyncDeltaSequenceNo_set(swigCPtr, this, value);
  }

  public int getSyncDeltaSequenceNo() {
    return ThostTradeApiJNI.CThostFtdcSyncDeltaDepthMarketDataField_SyncDeltaSequenceNo_get(swigCPtr, this);
  }

  public CThostFtdcSyncDeltaDepthMarketDataField() {
    this(ThostTradeApiJNI.new_CThostFtdcSyncDeltaDepthMarketDataField(), true);
  }

}
