/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcCFMMCBrokerKeyField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcCFMMCBrokerKeyField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcCFMMCBrokerKeyField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcCFMMCBrokerKeyField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_BrokerID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_ParticipantID_get(swigCPtr, this);
  }

  public void setCreateDate(String value) {
    ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_CreateDate_set(swigCPtr, this, value);
  }

  public String getCreateDate() {
    return ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_CreateDate_get(swigCPtr, this);
  }

  public void setCreateTime(String value) {
    ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_CreateTime_set(swigCPtr, this, value);
  }

  public String getCreateTime() {
    return ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_CreateTime_get(swigCPtr, this);
  }

  public void setKeyID(int value) {
    ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_KeyID_set(swigCPtr, this, value);
  }

  public int getKeyID() {
    return ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_KeyID_get(swigCPtr, this);
  }

  public void setCurrentKey(String value) {
    ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_CurrentKey_set(swigCPtr, this, value);
  }

  public String getCurrentKey() {
    return ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_CurrentKey_get(swigCPtr, this);
  }

  public void setKeyKind(char value) {
    ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_KeyKind_set(swigCPtr, this, value);
  }

  public char getKeyKind() {
    return ThostTradeApiJNI.CThostFtdcCFMMCBrokerKeyField_KeyKind_get(swigCPtr, this);
  }

  public CThostFtdcCFMMCBrokerKeyField() {
    this(ThostTradeApiJNI.new_CThostFtdcCFMMCBrokerKeyField(), true);
  }

}
