/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.optioninfo.jctp.ctp;

public class CThostFtdcUserSystemInfoField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcUserSystemInfoField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcUserSystemInfoField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ThostTradeApiJNI.delete_CThostFtdcUserSystemInfoField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_UserID_get(swigCPtr, this);
  }

  public void setClientSystemInfoLen(int value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientSystemInfoLen_set(swigCPtr, this, value);
  }

  public int getClientSystemInfoLen() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientSystemInfoLen_get(swigCPtr, this);
  }

  public void setClientSystemInfo(String value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientSystemInfo_set(swigCPtr, this, value);
  }

  public String getClientSystemInfo() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientSystemInfo_get(swigCPtr, this);
  }

  public void setReserve1(String value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_reserve1_set(swigCPtr, this, value);
  }

  public String getReserve1() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_reserve1_get(swigCPtr, this);
  }

  public void setClientIPPort(int value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientIPPort_set(swigCPtr, this, value);
  }

  public int getClientIPPort() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientIPPort_get(swigCPtr, this);
  }

  public void setClientLoginTime(String value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientLoginTime_set(swigCPtr, this, value);
  }

  public String getClientLoginTime() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientLoginTime_get(swigCPtr, this);
  }

  public void setClientAppID(String value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientAppID_set(swigCPtr, this, value);
  }

  public String getClientAppID() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientAppID_get(swigCPtr, this);
  }

  public void setClientPublicIP(String value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientPublicIP_set(swigCPtr, this, value);
  }

  public String getClientPublicIP() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientPublicIP_get(swigCPtr, this);
  }

  public void setClientLoginRemark(String value) {
    ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientLoginRemark_set(swigCPtr, this, value);
  }

  public String getClientLoginRemark() {
    return ThostTradeApiJNI.CThostFtdcUserSystemInfoField_ClientLoginRemark_get(swigCPtr, this);
  }

  public CThostFtdcUserSystemInfoField() {
    this(ThostTradeApiJNI.new_CThostFtdcUserSystemInfoField(), true);
  }

}
